#!/bin/bash

curl 'https://www.amazon.com/s?k=nvidia+rtx+3070&low-price=300&high-price=700' \
  -H 'authority: www.amazon.com' \
  -H 'rtt: 100' \
  -H 'downlink: 10' \
  -H 'ect: 4g' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-user: ?1' \
  -H 'sec-fetch-dest: document' \
  -H 'referer: https://www.amazon.com/' \
  -H 'accept-language: en-US,en;q=0.9,pt;q=0.8' \
  --compressed
