name: CI
on: [push]
jobs:

  build:
    name: Build and Test

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # CI is not free =P
        #os: [ ubuntu-latest, windows-latest, macos-latest ]
        os: [ ubuntu-latest ]
        #go: [ "1.13", "1.14", "1.15" ]
        go: [ "1.15" ]

    steps:

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: make test
